### ISSUE TITLE
Admin create problem관련 이슈

### ISSUE THREAD

**Issue by Anzanda** [skkuding/skku-coding-platform#129]
![image](https://user-images.githubusercontent.com/79851762/123655139-ae28b080-d869-11eb-962e-3ec1bdaf4c76.png)

1. create가 성공했을 때 위 그림처럼 succeed가 두 번 발생!

![image](https://user-images.githubusercontent.com/79851762/123656094-93a30700-d86a-11eb-8c9f-da639a1e3538.png)

2. displayID의 중복으로 create에 실패한 상황. 이 때도 succeed가 뜬다!

**Comment by ghdwlsrl3229** [comment]
이전에 저도 눈여겨봤던 부분이라 코멘트를 남깁니다.
이미 파악하셨을수도 있지만, 테스트케이스를 등록하는 createTestCase 함수와 문제를 등록하는 createProblem 함수가 별도로 호출되기 때문에 각 함수의 성공 여부가 2번 표시되는 것 같습니다. 
근본적인 구조를 바꾸지 않는 이상 백엔드에서 테스트케이스 등록와 문제를 등록하는 API를 하나로 통합한 API를 새로 만들거나, 혹은 api.js에서 ajax 함수를 손보는 것이 해결책이 될 수 있을 것 같습니다.

**Comment by dotoleeoak** [comment]
@ghdwlsrl3229 `createTestCase()`에서는 `$success()` alert 창을 띄우지 않는게 어떨까 싶습니다.
`createTestCase()`의 성공 여부는 `createProblem()`으로 넘겨서, 에러 핸들링과 alert 창 띄우는 걸 모두 `createProblem()`가 맡도록 하는거죠.

**Comment by minseo999** [comment]
Django to NestJS migration 예정으로, 필요없어진 이슈를 닫습니다.
