### ISSUE TITLE
변수명 통일

### ISSUE THREAD

**Issue by Jeongcc** [skkuding/skku-coding-platform#149]
Notice, Announcement -> Notice
Username, StudentID -> StudentID

**Comment by jimin9038** [comment]
Contest Clarification이 Admin에서는 Announcement로 보임 Clarification으로 모두 수정해야될듯

**Comment by minseo999** [comment]
Django to NestJS/Vue2 to Vue3 migration 예정으로, 필요없어진 이슈를 닫습니다.
