### ISSUE TITLE
서버 모니터링 시스템 구축

### ISSUE THREAD

**Issue by cranemont** [skkuding/skku-coding-platform#196]
트래픽 체크 및 지속적인 관리를 위한 서버 모니터링 시스템 구축

[netdata](https://www.netdata.cloud/)가 UX/UI가 가장 직관적이고 필요한 기능이 전부 있어서 가장 적합할 듯 합니다.

### 후보 비교
https://tidal-brook-54f.notion.site/783be0f03dd042af907e5e9740acbb57?v=a7965f12cf584a0bb8937d91e911727f

**Comment by cranemont** [comment]
netData는 Host machine의 상태만 확인 가능합니다. 컨테이너별 상태를 모니터링하기 위해 Cadvisor를 사용합니다.

***참고***
- [https://blog.naver.com/PostView.nhn?blogId=alice_k106&logNo=221090348538&proxyReferer=https:%2F%2Fwww.google.com%2F](url)
- [https://imbang.net/2019/06/21/cadvisor-prometheus-grafana-%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EC%BB%A8%ED%85%8C%EC%9D%B4%EB%84%88-%EB%AA%A8%EB%8B%88%ED%84%B0%EB%A7%81/](url)

**Comment by dotoleeoak** [comment]
@cranemont sentry는 어떻게 생각하시나요??

**Comment by cranemont** [comment]
@dotoleeoak 찾아봤는데 sentry랑 Cadvisor, node exporter가 성격이 조금씩 다르네요

- sentry: user, service error log 수집 시스템
- Cadvisor: docker container 리소스 모니터링 시스템
- node exporter: host machine 리소스 모니터링 시스템

이중 먼저 필요한건 sentry같아 보여요! 우선 sentry 먼저 도입하고
추후에 Cadvisor+node exporter조합으로 리소스 모니터링 시스템을 구축하는건 어떨까요?

**Comment by dotoleeoak** [comment]
@cranemont 넵 좋아요~

**Comment by cranemont** [comment]
system-management 레포지토리에서 진행합니다
