### ISSUE TITLE
CSS Initialization

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/skku-coding-platform#207]
https://blog.tommyzip.co.kr/code/css-initialization-guide/
브라우저 호환을 위한 CSS 초기화 적용

**Comment by jimin9038** [comment]
Tailwind 도입하면 자동으로 해결되는 문제가 맞죠 이거? 
https://tailwindcss.com/docs/preflight

**Comment by dotoleeoak** [comment]
@jimin9038 넹~
