### ISSUE TITLE
상황별 DB 조회 페이지

### ISSUE THREAD

**Issue by Jeongcc** [skkuding/skku-coding-platform#23]
디자인팀 : UI 구성
프론트엔드 : UI대로 페이지 제작
백엔드 : 학년별, 전공별, 복수전공별 등의 상황에 따른 db 조회 api 만들기

**Comment by nhjbest24** [comment]
^^7

**Comment by Jeongcc** [comment]
통계 자료로 사용할 Box Flot 에 대한 설명
https://leebaro.tistory.com/entry/%EB%B0%95%EC%8A%A4-%ED%94%8C%EB%A1%AFbox-plot-%EC%84%A4%EB%AA%85

Vue에서 Box Flot 구현하기
https://www.telerik.com/kendo-vue-ui/components/charts/series-types/box-plot/

**Comment by minseo999** [comment]
구현하지 않게된 기능과 관련된 이슈를 닫습니다.
