### ISSUE TITLE
Provides DB seed command

### ISSUE THREAD

**Issue by jimin9038** [skkuding/skku-coding-platform#288]
현재는 E2E Test나 프론트엔드 테스트 중에 일일이 UI나 API를 통해 데이터를 등록해야 합니다.
초기 데이터 설정을 통해 빠르게 UI와 API를 확인할 수 있도록 DB Seed 커맨드가 있으면 좋을 것 같습니다.

**Comment by dotoleeoak** [comment]
안그래도 구현하려던 참이었는데, django seed랑 faker로 만들까 고민 중이에요.
