### ISSUE TITLE
Get previous & next announcement in nicer way

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/skku-coding-platform#83]
```python
# announcement/views/oj.py
# AnnouncementDetailAPI
data["current"] = AnnouncementSerializer(announcement).data
prev_announcements = Announcement.objects.filter(id__lt=id, visible=True)
if prev_announcements:
    data["previous"] = AnnouncementSerializer(prev_announcements.latest("create_time")).data
next_announcements = Announcement.objects.filter(id__gt=id, visible=True)
if next_announcements:
    data["next"] = AnnouncementSerializer(next_announcements.earliest("create_time")).data
return self.success(data)
```

현재 위와 같이 구현되어있지만, Django에 바로 이전/다음 object를 가져오는 method가 내장되어있음.
해당 method를 사용한 구현으로 변경할 것.

https://stackoverflow.com/questions/6021694/getting-next-and-previous-objects-in-django

**Comment by dotoleeoak** [comment]
더불어 현재 `APIView` 클래스에 구현되어있는 `paginate_data`를 drf에 내장된 pagination으로 대체하는 것도 고려해보자. ( `PageNumberPagination` & `LimitOffsetPagination`)

**Comment by minseo999** [comment]
https://docs.djangoproject.com/en/3.1/ref/models/instances/#django.db.models.Model.get_previous_by_FOO
이전/다음 객체를 가져오는 해당 method는 not null인 Date* 타입의 필드를 기준으로만 이전/다음 객체를 가져올 수 있다고합니다
공지사항의 경우에는 같은 날짜의 여러 게시글이 있을 경우가 있으니까 그대로 두는게 낫지 않을까요?!

**Comment by dotoleeoak** [comment]
@minseo999 일반적으로 `Date()` 객체라 함은 millisecond 단위로 저장되기 때문에 날짜 뿐만 아니라 시, 분, 초도 구분하는 걸로 알고 있습니다. 공지사항도 시간 순으로 정렬한다는 가정 하에 문제 없을 거 같아요.

**Comment by minseo999** [comment]
Django to NestJS migration 예정으로, 필요없어진 이슈를 닫습니다.
